workflows:
  android-build:
    name: Android build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --target lib/main.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
